upstream api {
    server api:8000;
    keepalive 32;
}

upstream frontend {
    server frontend:3000;
    keepalive 16;
}

server {
    listen 80;
    server_name localhost;

    # Upload PDF size
    client_max_body_size 25M;

    location /api/ {
        rewrite ^/api(/.*)$ $1 break;
        proxy_pass         http://api;
        proxy_http_version 1.1;
        proxy_set_header   Connection "";
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
    }

    location / {
        proxy_pass         http://frontend;
        proxy_http_version 1.1;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Host $host;
    }
}